### PR TITLE
Facelift

### PR DESCRIPTION
**Pull request by imacrayon**
I've updated the look and feel of the site for 2020.

I'm not sure how this site get deployed but I added the front-end assets to `.gitignore` so that running `npm run production` will put them where they need to be. Alternatively you could run NPM locally and then deploy the assets pre-built.

### CODE REVIEW

**Comment by imacrayon** [comment]
image

**Comment by sethetter** [comment]
Screenshots look awesome! Just trying to run it locally to make sure it's all good. I also don't have access to this site's heroku account, so hopefully there's some auto deploy setup, lol.

**Comment by sethetter** [comment]
💯! Got it running locally. I'm not sure how this is deployed yet, looks like heroku, but we'll get that sorted.

New design is fantastic, thanks Christian!

**Review by sethetter — APPROVED** [review]

**Comment by sethetter** [comment]
@jcbwlkr do you have access to this heroku project? Do we need to add `npm i && npm run production` to the deploy pipeline somewhere?

**Comment by jcbwlkr** [comment]
@sethetter yeah heroku automatically deploys new commits to `master`. Right now it sees that it's a Go app because of `go.mod` and just compiles it and created a default `Procfile` automatically. Honestly I'm not sure what to do to have it run a node precompile step. I'll look but in the meantime I'll add you as a heroku maintainer

**Pull request merged**
