### PR TITLE
Adding Twitter tags

### PR DESCRIPTION
**Pull request by KatherineMichel**

### CODE REVIEW

**Comment by KatherineMichel** [comment]
Oops, I don't think svg will work for cards.

**Comment by jcbwlkr** [comment]
@KatherineMichel is this ready to merge? I wasn't sure because of your comment about svg before

**Comment by KatherineMichel** [comment]
@jcbwlkr I think this is ready to be merged. I added a jpg and changed the image paths

**Comment by jcbwlkr** [comment]
Thanks!

**Pull request merged**
