### PR TITLE
Fixing pic size

### PR DESCRIPTION
**Pull request by KatherineMichel**
This update should fix pic size.

### CODE REVIEW

**Comment by jcbwlkr** [comment]
So for some reason this didn't work when I ran it locally. I tried my hand at another approach that uses an SVG version of the logo with `width: 90%` and `max-width: 800px`. It's at https://github.com/devict/hacktoberfest/commit/8a5139beb1a9295d2d27268d948f5ce91a7b926a if you want to check it out.

Here's how it looks at different breakpoints. What do you think?

Large laptop 1440px
hacktoberfest-laptop-1440

Smaller laptop 1024px
hacktoberfest-laptop-1024

Tablet 768px
hacktoberfest-tablet-768

Mobile device 375px
hacktoberfest-mobile-375

**Comment by KatherineMichel** [comment]
I think those look good. I think the pull request should work now though.

**Comment by jcbwlkr** [comment]
I looked at https://katherinemichel.github.io/hacktoberfest-website-redesign/ and I see now what you were going for by moving the image up so the text is above the fold. I didn't get it before but I do now.

I do not think the logo should be cut off on the top like it is. I have tweaked mine a little to increase the size so it takes up more of the available room but is still wholly visible.
hacktoberfest-laptop-1440 2

What I like about this approach is

1. Smaller / simpler markup. It's easier to see what's happening because it's a `<header>` with an `` instead of nested `<divs>` that have a background image
2. It scales better: vector graphics like SVG scale up and down without loss of image quality. Also the whole logo is visible at any screen size
3. Initial load speed should be better. The JPG is 272k while the svg is only 29k.

If you're okay with it I will merge that `header` branch and close this PR.

**Comment by KatherineMichel** [comment]
Sounds good to me!

**Pull request closed without merging**
